language: csharp
mono: none
dist: xenial
os: linux
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: 3.1/stable
install:
  - 'export PATH="$PATH:/home/travis/.dotnet/tools"'
  - 'export PATH="$PATH:$HOME/.local/bin"'
  - pip install --user awscli
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
jobs:
  include:
    - stage: test_unit_testing
      name: Run tests on NosCore.Packets
      script:
        - dotnet restore
        - dotnet build
        - dotnet test test/NosCore.Packets.Tests -v m
    - stage: test_validate_documentation
      name: Build Packet List documentation generator
      script:
        - dotnet restore
        - >-
          dotnet build src/NosCore.Packets.Documentator -c Release -o
          /tmp/documentator
        - >-
          dotnet /tmp/documentator/NosCore.Packets.Documentator.dll
          /tmp/PACKET_LIST_TEST.md
    - stage: release_nuget_packages
      name: Build NosCore.Packets package (nuget)
      if: (tag =~ /^((\d+\.)+\d+)/)
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet pack -c Release -o /tmp/nupkgs -v m
      deploy:
        provider: script
        edge: true
        script: bash scripts/deploy-nuget.sh
        cleanup: false
        'on':
          tags: true
    - stage: release_github
      name: Publish Release on GitHub
      if: (tag =~ /^((\d+\.)+\d+)/)
      script:
        - dotnet restore
        - dotnet build -c Release
        - dotnet pack -c Release -o /tmp/nupkgs -v m
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file: /tmp/nupkgs/NosCore.Packets.${TRAVIS_TAG}.nupkg
        cleanup: false
        'on':
          tags: true
